# This workflow will publish the bot

name: Publish Twilio Bot

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Bot Unique Name'
        required: true
        default: 'Payment_Arrangement_V2_Bot'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install twilio cli and run deploy command
        env:
         TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
         TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
         TWILIO_API_SECRET: ${{secrets.TWILIO_API_SECRET}}
        run: npm install twilio-cli -g && twilio plugins:install @dabblelab/plugin-autopilot && cd  ./${{ github.event.inputs.name }} && twilio autopilot:deploy && twilio api:serverless:v1:services:update --sid ZS51c488ab556f1daf9352eba87668f672 --ui-editable true
